name: deeplearning-local
channels:
  - defaults
dependencies:
  # --- CONDA PACKAGES ---
  - python=3.10
  - ipykernel
  - ipywidgets  
  - pandas
  - scikit-learn
  - python-Levenshtein
  # --- PIP PACKAGES ---
  - pip
  - pip:
    - kagglehub