name: deeplearning-gpu
channels:
  # Prioritize Tsinghua Mirrors for speed in China
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - defaults
dependencies:
  # --- CONDA PACKAGES (Core & GPU) ---
  - python=3.10
  - ipykernel
  - ipywidgets
  - pandas
  - scikit-learn
  - jupyter
  
  # --- PIP PACKAGES ---
  - pip
  - pip:
    # Force pip to use Tsinghua mirror for these packages
    - --index-url https://pypi.tuna.tsinghua.edu.cn/simple
    - torch
    - kagglehub
    - python-Levenshtein
    - transformers
    - accelerate
    - protobuf 
    - sentencepiece
    - sacremoses
    - notebook
    - bert_score
    - evaluate
    - tqdm
    - seaborn